format = """
[â–‘â–’â–“](light_blue)\
$directory\
[î‚´](fg:light_blue bg:slate_blue )\
$git_state\
$git_branch\
$git_status\
[î‚´](fg:slate_blue bg:dark_blue )\
$python\
$conda\
[î‚´](fg:dark_blue)\
\n$character"""

palette = "current"

[directory]
style = "fg:navy bg:light_blue"
format = "[ $path ]($style)"
truncation_symbol = ".../"

[git_branch]
symbol = "ï˜"
style = "fg:light_blue bg:slate_blue"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:light_blue bg:slate_blue"
format = '[(($conflicted )($stashed )($deleted )($renamed )($modified )($staged )($untracked )$ahead_behind )]($style)'
ahead = 'â‡¡$count'
diverged = 'â‡•â‡¡$ahead_count â‡£$behind_count'
behind = 'â‡£$count'
untracked = '?$count'
modified = '!$count'
stashed = '*$count'
staged = '+$count'
conflicted = "=$count"
deleted = "âœ˜$count"
renamed = "Â»$count"

[python]
symbol = "\ue73c "
style = "fg:light_blue bg:dark_blue"
version_format = 'v$major.$minor'
format = '[ $symbol( $virtualenv )\($version\) ]($style)'

[conda]
symbol = "ğŸ "

[palettes.current]
black = "#000000"
white_blue = "#e3e5e5"
light_blue = "#91b6ff"
slate_blue = "#394260"
dark_blue = "#212736"
navy = "#1d2230"
grey = "#a0a9cb"
